# tmp
FROM nvcr.io/nvidian/ct-toronto-ai/stylegan:0.4
MAINTAINER seungwookk@nvidia.com


WORKDIR /workspace
COPY . .
RUN pip install matplotlib==3.3.3
#RUN pip install torch==1.7.1 torchvision==0.8.2
#RUN rm -fr /tmp/torch_extensions/
#RUN cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
